### ISSUE TITLE
cannot import name 'builder' from 'google.protobuf.internal' (/home/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

### ISSUE THREAD

**Issue by magicwang1111** [chaojie/ComfyUI-Moore-AnimateAnyone#13]
Traceback (most recent call last):
  File "/mnt/data/wangxi/Comfyui/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/data/wangxi/Comfyui/custom_nodes/ComfyUI-Moore-AnimateAnyone/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "/mnt/data/wangxi/Comfyui/custom_nodes/ComfyUI-Moore-AnimateAnyone/nodes.py", line 24, in <module>
    from src.pipelines.pipeline_pose2vid_long import Pose2VideoPipeline
  File "/mnt/data/wangxi/Comfyui/custom_nodes/ComfyUI-Moore-AnimateAnyone/src/pipelines/pipeline_pose2vid_long.py", line 23, in <module>
    from transformers import CLIPImageProcessor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1077, in __getattr__
    value = getattr(module, name)
  File "/home/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' (/home/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

Cannot import /mnt/data/wangxi/Comfyui/custom_nodes/ComfyUI-Moore-AnimateAnyone module for custom nodes: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' (/home/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

Import times for custom nodes:
   0.5 seconds (IMPORT FAILED): /mnt/data/wangxi/Comfyui/custom_nodes/ComfyUI-Moore-AnimateAnyone

Starting server

To see the GUI go to: http://0.0.0.0:7864

**Comment by magicwang1111** [comment]
(comfyui) [wangxi@v100-4 Comfyui]$ pip show transformers
Name: transformers
Version: 4.30.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /mnt/data/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: image-reward, lama-cleaner, lycoris-lora
(comfyui) [wangxi@v100-4 Comfyui]$ pip show protobuf
Name: protobuf
Version: 3.19.6
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author:
Author-email:
License: 3-Clause BSD License
Location: /mnt/data/wangxi/miniconda3/envs/comfyui/lib/python3.10/site-packages
Requires:
Required-by: mediapipe, onnxruntime, onnxruntime-gpu, open-clip-torch, streamlit, tb-nightly, tensorboard, tensorboardX, tensorflow, wandb
(comfyui) [wangxi@v100-4 Comfyui]$
